service: cloud-cluster

provider:
  name: aws
  runtime: java8
  timeout: 30
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: ['cognito-idp:ListUsers']
      Resource: 'arn:aws:cognito-idp:eu-west-1:432337707074:userpool/eu-west-1_4KfOFr5m3'
    - Effect: Allow
      Action: ['s3:*']
      Resource:
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: Info
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: Info
              - '/*'

package:
  artifact: target/cloud-resource-finder-1.0-SNAPSHOT.jar

functions:

  resourceInfoFinder:
    handler: com.cluster.api.ApiReactor
    environment:
      BUCKET: { Ref: Info }
    events:
      - http:
          path: accounts
          cors: true
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:432337707074:userpool/eu-west-1_4KfOFr5m3
      - http:
          path: accounts/{accountId}
          cors: true
          method: put
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-1:432337707074:userpool/eu-west-1_4KfOFr5m3

resources:
  Resources:
    Info:
      Type: AWS::S3::Bucket